POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Second test",
    "author": "Maria",
    "url": "www.bing.com",
    "likes": 1
}

###

GET http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
